### ISSUE TITLE
Number formatter?

### ISSUE THREAD

**Issue by PatMurrayDEV** [BalestraPatrick/EmergencyAPI#1]
In the [JSON output](http://emergency-phone-numbers.herokuapp.com/country/AU) your have Australia returning `0` for emergency numbers. I see in the [Datasource](https://github.com/BalestraPatrick/EmergencyAPI/blob/master/App/Datasource.swift) you have it correctly listed as `000`. 

``` JSON
{
    "code": "AU",
    "fire": 0,
    "police": 0,
    "name": "Australia",
    "medical": 0
}
```

Should be:

``` JSON
{
    "code": "AU",
    "fire": 000,
    "police": 000,
    "name": "Australia",
    "medical": 000
}
```

Datasource:

``` Swift
Country(name: "Australia", code: "AU", police: 000, medical: 000, fire: 000).self,
```

Regarding emergency number's the number of repeat digits is important. Any plans for how to address this?  (I'm fairly sure Australia is the only one with the repeat 0 problem though 😕)

**Comment by PatMurrayDEV** [comment]
It appears Russia suffers from this as well (as it has a leading zero). 

``` Swift
Country(name: "Russia", code: "RU", police: 02, medical: 02, fire: 02).self,
```

JSON output:

``` JSON
{
    "code":"RU",
    "fire":2,
    "police":2,
    "name":"Russia",
    "medical":2
}
```

Might need to think about moving the phone numbers (currently ints) to Strings to accomodate leading zeroes.

**Comment by BalestraPatrick** [comment]
Hey, thanks for opening the issue! When deciding to got with an Int instead of a String for the phone numbers I only thought about the possible overflow of the Int. Not seeing any number longer than 5-digits I decided to go with the Int.
You show an edge case and I think it's worth switching to store the phone number as a String. I will create a PR to address this issue soon 👍
